### ISSUE TITLE
Table is not a constructor

### ISSUE THREAD

**Issue by McGern** [victorquinn/dynasty#108]
Hi,

Thanks for the library. Trying to use this within an Alexa lambda function and am testing simple functions to see if I am connecting properly. I can successfully create a table and see the result in DynamoDB, but when I try to use dynasty.table(tableName) it throw a "Table is not a constructor" error. I am using the same syntax that I say on this page http://dynastyjs.com/table.html

At the moment I am running the script locally, but connecting to DynamoDB on aws (not locally).

Any insight would be very much appreciated.

Thanks,
Jarrod

**Comment by McGern** [comment]
Think the issue was to do with the lowercase of the table.js file and how the "lib" folder is imported. There are a bunch of SFConflict files (some uppercase Table.js and some lowercase table.js). 

The dynasty.js file has the line

Table = lib.Table

and (in my case) changing lib.Table to lib.table solved it.

**Comment by aterreno** [comment]
Same, not sure what those SFConflict files but it seems like when @victorquinn released the last time something got messed up.

**Comment by victorquinn** [comment]
Hmm, sorry for this, investigating now!

**Comment by victorquinn** [comment]
Ok try now, sorry, I think something went awry pushing from my other machine. In brief, git has crappy handling of upper and lowercase file names (it doesn't distinguish between them) so it seems for some reason it changed the filename from lib.Table to lib.table on my other machine. Mixed up in that sauce are those weird hidden SFConflict files that seemingly came from Seafile, my file syncing service.

Anyway, I bumped the version number, rebuilt it, and re-pushed it and things should be copacetic now with 0.3.12 but let me know if they aren't and we can re-open this!

**Comment by McGern** [comment]
Brilliant. Thanks very much for doing that so quickly, it's really appreciated. Tested and works fine.

Thanks for the work you have put into making this library so simple to work with.
