### ISSUE TITLE
Got An error on M type

### ISSUE THREAD

**Issue by jaecSolutions** [victorquinn/dynasty#45]
I have a M type on my dynamoDB  

on translator got this error
throw new Error('Non Compatible Field [not "S"|"N"|"NS"|"SS"]: ' + key);

**Comment by victorquinn** [comment]
Believe it or not, this library was written back when those were the only data types Dynamo supported. Now it includes [a whole bunch more](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DataFormat.html)! 

We'll have to add data translators for these items, I'm bumping this up to the very short list to get remedied ASAP.

**Comment by victorquinn** [comment]
Closing as this was fixed in #65
