### ISSUE TITLE
doc about error handling?

### ISSUE THREAD

**Issue by Vuuo** [victorquinn/dynasty#54]
I couldn't find any doc about how to handle errors for dynasty. Since it's promise-based, I'm guessing it supports all the error handling functions come with promise. `catch`, `fail`, and `done`.

Please confirm. And maybe update the doc regarding error handling?

Thanks

**Comment by victorquinn** [comment]
Hi @Vuuo yes, Dynasty does conform to the [Promises/A+ spec](https://promisesaplus.com) so it supports things like `catch` and `fail` and `done`.

In fact it's using the awesome [Bluebird Promise library](https://github.com/petkaantonov/bluebird/blob/master/API.md) under the hood so every Promise returned from Dynasty has all the functionality of a Bluebird promise.

Will add a todo to update the docs to reflect this.
