### ISSUE TITLE
Is coffee-script really a dependency?

### ISSUE THREAD

**Issue by cmawhorter** [victorquinn/dynasty#76]
In package.json, coffee-script is a dependency instead of a dev dependency.  Is this a mistake?

**Comment by victorquinn** [comment]
Yes it is a mistake! 

Well, better put, it's a relic, used to be coffeescript than ran using coffeescript as a dependency after download. At some point I switched to compiling before upload to npm making it no longer necessary as a dependency. 

Shouldn't be there.
