### ISSUE TITLE
Does this work on the browser?

### ISSUE THREAD

**Issue by breandr** [victorquinn/dynasty#86]
Does this work on the browser, or just node?

**Comment by victorquinn** [comment]
That's a great question and one I don't have the answer for!

It was developed for Node and tested there, but I can't think of any reason why it shouldn't work in the browser. Dynasty isn't dependent on any Node specific libraries or other C-based libraries which wouldn't work in the browser.

I'd be a bit confused about the security model (as direct client-side access to the DB is generally not a great idea) but in theory it should probably work. Let me know how it goes!

**Comment by breandr** [comment]
Thanks.

Direct DynamoDB access can be achieved by acquiring creds via Cognito. You just have to ensure you have your IAM policies scoped appropriately.

**Comment by victorquinn** [comment]
@breandr Ahhhh hadn't thought of that, very clever!

Out of curiosity, did you try it? And if so did it work?

**Comment by breandr** [comment]
No I didn't try this lib on the client. As you said, it likely would have
worked, but I want to keep it as thin as possible. I ripped the wrap/unwrap
functionality from another lib and just going to use that with the raw SDK
for now. I might add a layer later to make it more developer friendly, if
the SDK's API becomes too cumbersome.
