### ISSUE TITLE
toDynamo array data types cause DynamoDB insertion errors

### ISSUE THREAD

**Issue by mattvukas** [victorquinn/dynasty#90]
In data-translators.js, in the toDynamo function, there is some logic that picks a Dynamo data type for an inputted JavaScript array. If the array contains all numbers, it gets the `NS` or Number Set data type. If the array contains all strings, it gets the `SS` or String Set data type. And then if the array contains only objects, it gets the `L` or List data type.

The problem is that Number Set or String Set data types require every element of the array to be unique, and the insertion/update will fail if the JavaScript array contains duplicates. So using Dynasty there's no way to save a JavaScript array with duplicate values. I don't see a downside to simply assigning the List data type to every array, since it can handle various data types within, has no restriction on duplicates, and is even suggested as the most similar to a JSON array in the [AWS doc on this topic](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html#HowItWorks.DataTypes).

Alternatively, in the logic that checks for all numbers or all strings in an array before assigning a Set data type, you could also check that the array only contains unique values. But I think using List data type for all arrays may be simpler. 

Link to code:
https://github.com/victorquinn/dynasty/blob/master/src/lib/data-translators.coffee#L49

**Comment by pgoldweic** [comment]
Has this ever been fixed in your code? I see that the code has been updated, but I'm still running into this same issue when grabbing your latest source (that is, number sets are being used instead of lists everywhere). My data contains arrays of all numbers or all strings which in some cases contains duplicate values, and as @mattvukas described back in January, it is impossible to save this type of data using dynasty.

**Comment by pgoldweic** [comment]
So I proceeded to fix this in my own version with @mattvukas suggestion (using the list data type). The resulting toDynamo function looks like:
    
     toDynamo = function(item) {
        var array, key, map, num, obj, value, _i, _len;
        if (_.isArray(item)) {
            array = [];
            for (_i = 0, _len = item.length; _i < _len; _i++) {
              value = item[_i];
              array.push(toDynamo(value));
            }
            return obj = {
              'L': array
            };
        } else if (_.isNumber(item)) {
          return obj = {
            'N': item.toString()
          };
        } else if (_.isString(item)) {
          return obj = {
            'S': item
          };
        } else if (_.isBoolean(item)) {
          return obj = {
            'BOOL': item
          };
        } else if (_.isObject(item)) {
          map = {};
          for (key in item) {
            value = item[key];
            map[key] = toDynamo(value);
          }
          return obj = {
            'M': map
          };
        } else if (item === null) {
          return obj = {
            'NULL': true
          };
        } else if (!item) {
          throw new TypeError("toDynamo() does not support mapping " + (util.inspect(item)));
        }
      };

Would be great if you could incorporate this fix in your repository. Thanks.

**Comment by victorquinn** [comment]
Great point @pgoldweic and @mattvukas and apologies I didn't get to it sooner.

Just pushed code with this fix, will deploy to npm once tests pass!

**Comment by victorquinn** [comment]
ok this is live on npm as `0.3.8` and it got a minor version update as this is potentially backwards incompatible with previous versions as it changes the datatypes that are sent to dynamo
